<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Arbiter</AssemblyName>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <Company>Erik 'SiLo' Rogers</Company>
        <Product>Arbiter</Product>
        <AssemblyVersion>1.8.2</AssemblyVersion>
        <FileVersion>1.8.2</FileVersion>
        <ApplicationIcon>Assets\arbiter.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
        <AvaloniaResource Include="Themes\**"/>
        <None Include="..\THIRD-PARTY-NOTICES.md"
              Link="THIRD-PARTY-NOTICES.md"
              CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.18" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.18" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.18">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
        <PackageReference Include="Xaml.Behaviors.Interactions" Version="11.3.9.6" />
        <PackageReference Include="Xaml.Behaviors.Interactions.Custom" Version="11.3.9.6" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Arbiter.Interop\Arbiter.Interop.csproj" />
      <ProjectReference Include="..\Arbiter.Imaging\Arbiter.Imaging.csproj" />
      <ProjectReference Include="..\Arbiter.Json\Arbiter.Json.csproj" />
      <ProjectReference Include="..\Arbiter.Net\Arbiter.Net.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\ConsoleLogView.axaml.cs">
        <DependentUpon>ConsoleLog.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\InspectorView.axaml.cs">
        <DependentUpon>PacketInspector.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\HexView.axaml.cs">
        <DependentUpon>RawHexDisplay.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\TraceView.axaml.cs">
        <DependentUpon>TraceLog.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
